spring:
  application:
    name: holo_backend
  data:
    mongodb:
      uri: ${HOLO_DATABASE_URL:mongodb://localhost:27017/holo_db}
      database: ${HOLO_DATABASE_SCHEMA:holo_db}

jwt:
   secret: ${HOLO_JWT_SECRET:holo_jwt_secret}
   expiration: ${HOLO_JWT_EXPIRATION:150}
server:
  port: 56932
logging:
  level:
    root: info
    org.holo: info
    org.springframework.data.mongodb: debug
springdoc:
   api-docs:
     enabled: false
